### ISSUE TITLE
Player still moving on lilypad

### ISSUE THREAD

**Issue by Bejno** [Turnary-Games/Battery-Golem#7] opened 2015-10-16 07:18 UTC
If you use the fan while the lilypad is going into an object the player will keep on moving.

![player still moving on lilypad](https://cloud.githubusercontent.com/assets/12370172/10535861/aa42e104-73e6-11e5-9f42-6f049004f205.gif)

**Comment by applejag** [comment] 2015-10-16 13:28
Duplicate of #5

**Closed as completed** 2016-03-30 12:11 UTC
Labels: bug, duplicate
